name: Deploy Vue App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4


    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22


    - name: Install dependencies
      run: npm install


    - name: Write production env
      run: |
        cat <<EOF > .env.production
        VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}
        VITE_PUSHER_APP_KEY=${{ secrets.VITE_PUSHER_APP_KEY }}
        VITE_PUSHER_APP_CLUSTER=${{ secrets.VITE_PUSHER_APP_CLUSTER }}
        EOF

    - name: Build Vue
      run: npm run build

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: vue-dist
        path: dist
  
  deploy:
    needs: build
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: vue-dist
          path: dist
      - name: Upload dist folder
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          source: "dist/*,dist/.htaccess"
          target: "~/domains/solvaconseil.fr/public_html/crm_frontend/"
          overwrite: true